/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: products.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "products.pb-c.h"
void   product__init
                     (Product         *message)
{
  static const Product init_value = PRODUCT__INIT;
  *message = init_value;
}
size_t product__get_packed_size
                     (const Product *message)
{
  assert(message->base.descriptor == &product__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t product__pack
                     (const Product *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &product__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t product__pack_to_buffer
                     (const Product *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &product__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Product *
       product__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Product *)
     protobuf_c_message_unpack (&product__descriptor,
                                allocator, len, data);
}
void   product__free_unpacked
                     (Product *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &product__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   product_list__init
                     (ProductList         *message)
{
  static const ProductList init_value = PRODUCT_LIST__INIT;
  *message = init_value;
}
size_t product_list__get_packed_size
                     (const ProductList *message)
{
  assert(message->base.descriptor == &product_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t product_list__pack
                     (const ProductList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &product_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t product_list__pack_to_buffer
                     (const ProductList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &product_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProductList *
       product_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProductList *)
     protobuf_c_message_unpack (&product_list__descriptor,
                                allocator, len, data);
}
void   product_list__free_unpacked
                     (ProductList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &product_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor product__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Product, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Product, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "description",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Product, description),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "price",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Product, price),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "quantity",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Product, quantity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned product__field_indices_by_name[] = {
  2,   /* field[2] = description */
  0,   /* field[0] = id */
  1,   /* field[1] = name */
  3,   /* field[3] = price */
  4,   /* field[4] = quantity */
};
static const ProtobufCIntRange product__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor product__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Product",
  "Product",
  "Product",
  "",
  sizeof(Product),
  5,
  product__field_descriptors,
  product__field_indices_by_name,
  1,  product__number_ranges,
  (ProtobufCMessageInit) product__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor product_list__field_descriptors[1] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ProductList, n_data),
    offsetof(ProductList, data),
    &product__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned product_list__field_indices_by_name[] = {
  0,   /* field[0] = data */
};
static const ProtobufCIntRange product_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor product_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ProductList",
  "ProductList",
  "ProductList",
  "",
  sizeof(ProductList),
  1,
  product_list__field_descriptors,
  product_list__field_indices_by_name,
  1,  product_list__number_ranges,
  (ProtobufCMessageInit) product_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
